CREATE TABLE IF NOT EXISTS User (
    User_ID INT NOT NULL AUTO_INCREMENT,
    Profile_picture VARCHAR(255) NOT NULL,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Balance FLOAT NOT NULL DEFAULT 0.0,
    Email VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT userPK PRIMARY KEY (User_ID)
);

CREATE TABLE IF NOT EXISTS Listing (
    Listing_ID INT NOT NULL AUTO_INCREMENT,
    User_ID INT NOT NULL,
    Price FLOAT NOT NULL,
    Product_picture VARCHAR(255) NOT NULL,
    Listing_Name VARCHAR(100) NOT NULL,
    Listing_Description TEXT NOT NULL,
    onSale BOOLEAN NOT NULL DEFAULT TRUE,
    isClosed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT listingPK PRIMARY KEY (Listing_ID),
    CONSTRAINT listingFK FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Wishlist_Items (
    User_ID INT NOT NULL,
    Listing_ID INT NOT NULL,
    CONSTRAINT wishlistPK PRIMARY KEY (User_ID, Listing_ID),
    CONSTRAINT wishlistFK_User FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE,
    CONSTRAINT wishlistFK_Listing FOREIGN KEY (Listing_ID) REFERENCES Listing(Listing_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Orders (
    Order_ID INT NOT NULL AUTO_INCREMENT,
    User_ID INT NOT NULL,
    isClosed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT orderPK PRIMARY KEY (Order_ID),
    CONSTRAINT orderFK_User FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Order_Items (
    Order_ID INT NOT NULL,
    Listing_ID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    CONSTRAINT orderItemsPK PRIMARY KEY (Order_ID, Listing_ID),
    CONSTRAINT orderItemsFK_Order FOREIGN KEY (Order_ID) REFERENCES Orders(Order_ID) ON DELETE CASCADE,
    CONSTRAINT orderItemsFK_Listing FOREIGN KEY (Listing_ID) REFERENCES Listing(Listing_ID) ON DELETE CASCADE
);
